{{- if .Values.kafkatopic.enabled }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkatopic.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  partitions: {{ .Values.kafkatopic.partitions}}
  replicas: {{ .Values.kafkatopic.replicas }}
  config:
    retention.ms: {{ .Values.kafkatopic.retention_ms}}
    segment.bytes: 1073741824
{{- end }}
